# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-11 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_auto_20180611_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proapp.Profile'),
        ),
    ]
